spring:
  profiles:
    active:
      on-profile: develop
  datasource:
    username: ${DB_USER_ID}
    password: ${DB_USER_PASSWORD}
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_batch_fetch_size: 1000
      format_sql: true
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER # Swagger-ui
jwt:
  header: Bearer
  secret: ${JWT_SECRET}
  #hs256 algorithm
sns:
  google:
    url: https://accounts.google.com/o/oauth2/v2/auth
    client:
      id: ${GOOGLE_CLIENT_ID}
      secret: ${GOOGLE_CLIENT_SECRET}
    callback:
      url: ${GOOGLE_CALLBACK_URL}
    token:
      url: https://oauth2.googleapis.com/token
logging:
  slack:
    webhook-uri: ${WEBHOOK_URL}
  config: classpath:logback-spring.xml
  dir: ${LOG_DIR}
slack:
  url: ${ALERT_URL}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false
